### ISSUE TITLE
Error when you create new event

### ISSUE THREAD

**Issue by Odilbukh** [buildix/timex#29]
There is error when you create event. You can see it in screenshot. It seems it does not work with package z3d0x/filament-logger

![image](https://user-images.githubusercontent.com/22895615/218396852-57024d24-70df-40c0-8de6-42fa5bc01e07.png)

**Comment by mikrosmile** [comment]
Hello. Thank you. 
I'm not sure that it refers to timex actually. 

The error occurred because filament-logger (laravel logger) is using morphs and timex is using uuid - so it has to either timex database changes upon migration not to use uuid, or logger database adjustments to 


$table->nullableUuidMorphs('taggable');
